// creating data here instead of pulling from a database for more efficiency
const emblemData = [
  {
    name: 'Marth',
    image: '/assets/emblems/emblem_marth.png',
    title: 'Beginnings',
    stats: 'STR, DEX, SPD',
    maxStats: {
      hp: 0,
      str: 3,
      mag: 0,
      dex: 0,
      spd: 4,
      def: 0,
      res: 0,
      lck: 0,
      bld: 0,
    },
    skills: [
      {
        name: 'Perceptive',
        bondRank: '1',
        description:
          'If unit initiates combat, grants Avo+15. Avo increases with high speed(+1Avo for every 4 Spd)',
        type: 'Sync Skill, inheritable',
        sp: '500',
      },
      { name: 'Avoid+', bondRank: '', description: '', type: '', sp: '' },
      { name: 'Divine Speed', bondRank: '', description: '', type: '', sp: '' },
      {
        name: 'LodeStar Rush',
        bondRank: '',
        description: '',
        type: '',
        sp: '',
      },
      { name: 'Rapier', bondRank: '', description: '', type: '', sp: '' },
      {
        name: 'Sword Agility',
        bondRank: '',
        description: '',
        type: '',
        sp: '',
      },
      {
        name: 'Break Defenses',
        bondRank: '',
        description: '',
        type: '',
        sp: '',
      },
      { name: 'Unyielding', bondRank: '', description: '', type: '', sp: '' },
      { name: 'Sword Prof', bondRank: '', description: '', type: '', sp: '' },
      { name: 'Mercurius', bondRank: '', description: '', type: '', sp: '' },
      { name: 'Falchion', bondRank: '', description: '', type: '', sp: '' },
    ],
  },
  {
    name: 'Celica',
    image: '/assets/emblems/emblem_celica.png',
    title: 'Echoes',
    stats: 'STR, MAG, RES',
    maxStats: {
      hp: 0,
      str: 3,
      mag: 5,
      dex: 0,
      spd: 0,
      def: 0,
      res: 4,
      lck: 0,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
  },
  {
    name: 'Sigurd',
    image: '/assets/emblems/emblem_sigurd.png',

    title: 'the Holy War',
    stats: 'DEX, DEF, BLD, MOV',
    maxStats: {
      hp: 0,
      str: 4,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 4,
      res: 0,
      lck: 0,
      bld: 3,
      mov: 1,
    },
    skills: [],
  },
  {
    name: 'Leif',
    image: '/assets/emblems/emblem_leif.png',
    title: 'Genealogy',
    stats: 'HP, DEF, BLD',
    maxStats: {
      hp: 7,
      str: 0,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 3,
      res: 0,
      lck: 0,
      bld: 5,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Roy',
    image: '/assets/emblems/emblem_roy.png',
    title: 'Binding',
    stats: 'HP, STR, RES',
    maxStats: {
      hp: 10,
      str: 6,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 0,
      res: 3,
      lck: 0,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Lyn',
    image: '/assets/emblems/emblem_lyn.png',
    title: 'Blazing',
    stats: 'DEX, SPD, RES',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 0,
      dex: 4,
      spd: 5,
      def: 0,
      res: 3,
      lck: 0,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Eirika',
    image: '/assets/emblems/emblem_eirika.png',
    title: 'the Sacred',
    stats: 'MAG, DEX, LCK',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 3,
      dex: 4,
      spd: 0,
      def: 0,
      res: 0,
      lck: 10,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Ike',
    image: '/assets/emblems/emblem_ike.png',
    title: 'Radiance',
    stats: 'HP, STR, DEF',
    maxStats: {
      hp: 7,
      str: 4,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 5,
      res: 0,
      lck: 0,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Micaiah',
    image: '/assets/emblems/emblem_micaiah.png',
    title: 'Dawn',
    stats: 'MAG, RES, LCK',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 4,
      dex: 0,
      spd: 0,
      def: 0,
      res: 5,
      lck: 6,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Lucina',
    image: '/assets/emblems/emblem_lucina.png',
    title: 'Awakening',
    stats: 'DEX, SPD, LCK',
    skills: [],
    maxStats: {
      hp: 0,
      str: 0,
      mag: 0,
      dex: 5,
      spd: 4,
      def: 0,
      res: 0,
      lck: 6,
      bld: 0,
      mov: 0,
    },
  },
  {
    name: 'Corrin',
    image: '/assets/emblems/emblem_corrin.png',
    title: 'Fates',
    stats: 'HP, MAG, RES',
    skills: [],
    maxStats: {
      hp: 15,
      str: 0,
      mag: 4,
      dex: 0,
      spd: 0,
      def: 0,
      res: 3,
      lck: 0,
      bld: 0,
      mov: 0,
    },
  },
  {
    name: 'Byleth',
    image: '/assets/emblems/emblem_byleth.png',
    title: 'the Academy',
    stats: 'MAG, SPD, LCK',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 3,
      dex: 0,
      spd: 3,
      def: 0,
      res: 0,
      lck: 12,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
];

export default emblemData;
