// creating data here instead of pulling from a database for more efficiency
const emblemData = [
  {
    name: 'Marth',
    image: '/assets/emblems/emblem_marth.png',
    title: 'Beginnings',
    stats: 'STR, DEX, SPD',
    maxStats: {
      hp: 0,
      str: 3,
      mag: 0,
      dex: 4,
      spd: 4,
      def: 0,
      res: 0,
      lck: 0,
      bld: 0,
    },
    skills: [
      {
        name: 'Perceptive+',
        bondRank: [1, 16],
        description:
          'If unit initiates combat, grants Avo+30 (15, 30). Avo increases with high speed(+1Avo for every 4 Spd)',
        type: 'Sync',
        inherit: true,
        sp: '500',
      },
      {
        name: 'Avoid+',
        bondRank: [1, 4, 9, 14, 19],
        description:
          'Grants Avo+30 (10, 15, 20, 25, 30) at a cost of Crit-10 when using a sword.',
        type: '',
        sp: '',
      },
      {
        name: 'Divine Speed',
        bondRank: 1,
        description:
          'Unit performs an extra attack at 50% damage in combat. [Covert] If extra attack hits, poisons foe. [Dragon] Unit recovers HP equal to damage dealt by extra attack.',
        type: '',
        sp: '',
      },
      {
        name: 'LodeStar Rush',
        bondRank: 1,
        description: '',
        type: '',
        sp: '',
      },
      { name: 'Rapier', bondRank: '', description: '', type: '', sp: '' },
      {
        name: 'Sword Agility 5',
        bondRank: [2, 6, 8, 13, 17],
        description:
          'Grants Avo+30 (10, 15, 20, 25, 30) at a cost of Crit-10 when using a sword.',
        type: '',
        sp: '',
      },
      {
        name: 'Break Defenses',
        bondRank: '',
        description: '',
        type: '',
        sp: '',
      },
      {
        name: 'Unyielding++',
        bondRank: [7, 12, 18],
        description: '',
        type: '',
        sp: '',
      },
      { name: 'Sword Prof', bondRank: '', description: '', type: '', sp: '' },
      { name: 'Mercurius', bondRank: '', description: '', type: '', sp: '' },
      { name: 'Falchion', bondRank: '', description: '', type: '', sp: '' },
    ],
  },
  {
    name: 'Celica',
    image: '/assets/emblems/emblem_celica.png',
    title: 'Echoes',
    stats: 'STR, MAG, RES',
    maxStats: {
      hp: 0,
      str: 3,
      mag: 5,
      dex: 0,
      spd: 0,
      def: 0,
      res: 4,
      lck: 0,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
  },
  {
    name: 'Sigurd',
    image: '/assets/emblems/emblem_sigurd.png',

    title: 'the Holy War',
    stats: 'DEX, DEF, BLD, MOV',
    maxStats: {
      hp: 0,
      str: 4,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 4,
      res: 0,
      lck: 0,
      bld: 3,
      mov: 1,
    },
    skills: [],
  },
  {
    name: 'Leif',
    image: '/assets/emblems/emblem_leif.png',
    title: 'Genealogy',
    stats: 'HP, DEF, BLD',
    maxStats: {
      hp: 7,
      str: 0,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 3,
      res: 0,
      lck: 0,
      bld: 5,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Roy',
    image: '/assets/emblems/emblem_roy.png',
    title: 'Binding',
    stats: 'HP, STR, RES',
    maxStats: {
      hp: 10,
      str: 6,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 0,
      res: 3,
      lck: 0,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Lyn',
    image: '/assets/emblems/emblem_lyn.png',
    title: 'Blazing',
    stats: 'DEX, SPD, RES',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 0,
      dex: 4,
      spd: 5,
      def: 0,
      res: 3,
      lck: 0,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Eirika',
    image: '/assets/emblems/emblem_eirika.png',
    title: 'the Sacred',
    stats: 'MAG, DEX, LCK',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 3,
      dex: 4,
      spd: 0,
      def: 0,
      res: 0,
      lck: 10,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Ike',
    image: '/assets/emblems/emblem_ike.png',
    title: 'Radiance',
    stats: 'HP, STR, DEF',
    maxStats: {
      hp: 7,
      str: 4,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 5,
      res: 0,
      lck: 0,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Micaiah',
    image: '/assets/emblems/emblem_micaiah.png',
    title: 'Dawn',
    stats: 'MAG, RES, LCK',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 4,
      dex: 0,
      spd: 0,
      def: 0,
      res: 5,
      lck: 6,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Lucina',
    image: '/assets/emblems/emblem_lucina.png',
    title: 'Awakening',
    stats: 'DEX, SPD, LCK',
    skills: [],
    maxStats: {
      hp: 0,
      str: 0,
      mag: 0,
      dex: 5,
      spd: 4,
      def: 0,
      res: 0,
      lck: 6,
      bld: 0,
      mov: 0,
    },
  },
  {
    name: 'Corrin',
    image: '/assets/emblems/emblem_corrin.png',
    title: 'Fates',
    stats: 'HP, MAG, RES',
    skills: [],
    maxStats: {
      hp: 15,
      str: 0,
      mag: 4,
      dex: 0,
      spd: 0,
      def: 0,
      res: 3,
      lck: 0,
      bld: 0,
      mov: 0,
    },
  },
  {
    name: 'Byleth',
    image: '/assets/emblems/emblem_byleth.png',
    title: 'the Academy',
    stats: 'MAG, SPD, LCK',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 3,
      dex: 0,
      spd: 3,
      def: 0,
      res: 0,
      lck: 12,
      bld: 0,
      mov: 0,
    },
    skills: [],
  },
  {
    name: 'Fire Emblem',
    image: '/assets/emblems/alear-ring.png',
    title: 'Fire',
    stats: 'HP, SPD, DEF',
    maxStats: {
      hp: 15,
      str: 0,
      mag: 0,
      dex: 0,
      spd: 4,
      def: 4,
      res: 0,
      lck: 0,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
  },
  {
    name: 'Edelgard',
    image: '/assets/emblems/Edelgard.png',
    title: 'Rivals',
    stats: 'STR, DEX, DEF',
    maxStats: {
      hp: 0,
      str: 5,
      mag: 4,
      dex: 3,
      spd: 0,
      def: 0,
      res: 0,
      lck: 0,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
    dlc: true,
  },
  {
    name: 'Tiki',
    image: '/assets/emblems/Tiki.png',
    title: 'Dragons',
    stats: 'HP, DEF, LCK',
    maxStats: {
      hp: 10,
      str: 0,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 4,
      res: 0,
      lck: 10,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
    dlc: true,
  },
  {
    name: 'Hector',
    image: '/assets/emblems/hector.png',
    title: 'Strength',
    stats: 'STR, DEF, BLD',
    maxStats: {
      hp: 0,
      str: 4,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 5,
      res: 0,
      lck: 0,
      bld: 3,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
    dlc: true,
  },
  {
    name: 'Camilla',
    image: '/assets/emblems/camilla.png',
    title: 'Revelation',
    stats: 'HP, SPD, RES',
    maxStats: {
      hp: 7,
      str: 0,
      mag: 0,
      dex: 0,
      spd: 5,
      def: 0,
      res: 4,
      lck: 0,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
    dlc: true,
  },
  {
    name: 'Soren',
    image: '/assets/emblems/soren.png',
    title: 'Acumen',
    stats: 'MAG, DEX, RES',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 4,
      dex: 3,
      spd: 0,
      def: 0,
      res: 5,
      lck: 0,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
    dlc: true,
  },
  {
    name: 'Chrom',
    image: '/assets/emblems/chrom.png',
    title: 'Bonds',
    stats: 'STR, DEX, SPD',
    maxStats: {
      hp: 0,
      str: 3,
      mag: 0,
      dex: 5,
      spd: 4,
      def: 0,
      res: 0,
      lck: 0,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
    dlc: true,
  },
  {
    name: 'Veronica',
    image: '/assets/emblems/veronica.png',
    title: 'Heroes',
    stats: 'MAG, RES, LCK',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 5,
      dex: 0,
      spd: 0,
      def: 0,
      res: 4,
      lck: 6,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
    dlc: true,
  },
  {
    name: 'No Emblem',
    image: '/assets/misc/liberation.png',
    title: '',
    stats: '',
    maxStats: {
      hp: 0,
      str: 0,
      mag: 0,
      dex: 0,
      spd: 0,
      def: 0,
      res: 0,
      lck: 0,
      bld: 0,
    },
    skills: [{ name: '', bondRank: '', description: '', type: '', sp: '' }],
  },
];

export default emblemData;
