const unitData = [
  {
    name: 'Alear',
    image: '/assets/units/alearF.png',
    class: 'Dragon Child',
    innate: 'Sword',
    sp: 300,
    personal: {
      name: 'Divinely Inspiring',
      image: '',
      description: 'Adjacent allies deal +3 damage and take 1 less damage.',
    },
    origin: 'Lythos',
    growths: {
      hp: 60,
      str: 35,
      mag: 20,
      dex: 45,
      spd: 50,
      def: 40,
      res: 25,
      lck: 25,
      bld: 5,
    },
  },
  {
    name: 'Vander',
    image: '/assets/units/vander.png',
    class: 'Paladin',
    innate: 'Axe',
    sp: 300,
    personal: {
      name: 'Alabaster Duty',
      image: '',
      description:
        'If unit is adjacent to the Divine Dragon, grants crit+5 during combat to both of them.',
    },
    origin: 'Lythos',
    growths: {
      hp: 60,
      str: 25,
      mag: 10,
      dex: 25,
      spd: 35,
      def: 35,
      res: 20,
      lck: 10,
      bld: 5,
    },
  },
  {
    name: 'Clanne',
    image: '/assets/units/clanne.png',
    class: 'Mage',
    innate: 'Tome',
    sp: 300,
    personal: {
      name: 'Verdant Faith',
      image: '',
      description:
        'If unit is adjacent to the Divine Dragon, grants Hit+10 during combat to both of thme.',
    },
    origin: 'Lythos',
    growths: {
      hp: 40,
      str: 35,
      mag: 10,
      dex: 40,
      spd: 50,
      def: 30,
      res: 25,
      lck: 20,
      bld: 5,
    },
  },
  {
    name: 'Framme',
    image: '/assets/units/framme.png',
    class: 'Martial Monk',
    innate: 'Arts',
    sp: 300,
    personal: {
      name: 'Crimson Cheer',
      image: '',
      description:
        'If unit is adjacent to the Divine Dragon, grants Avo+10 during combat to both of them.',
    },
    origin: 'Lythos',
    growths: {
      hp: 55,
      str: 30,
      mag: 25,
      dex: 35,
      spd: 55,
      def: 25,
      res: 30,
      lck: 25,
      bld: 0,
    },
  },
  {
    name: 'Alfred',
    image: '/assets/units/alfred.png',
    class: 'Noble (Alfred)',
    innate: 'Lance',
    sp: 300,
    personal: {
      name: 'Self-Improver',
      image: '',
      description:
        'If unit uses Wait without attacking or using items, grants Str+2 for 1 turn.',
    },
    origin: 'Firene',
    growths: {
      hp: 65,
      str: 40,
      mag: 5,
      dex: 35,
      spd: 40,
      def: 40,
      res: 20,
      lck: 40,
      bld: 10,
    },
  },
  {
    name: 'Etie',
    image: '/assets/units/etie.png',
    class: 'Archer',
    innate: 'Bow',
    sp: 300,
    personal: {
      name: 'Energized',
      image: '',
      description:
        'When unit recovers HP using an item, grants Str+2 for 1 turn.',
    },
    origin: 'Firene',
    growths: {
      hp: 45,
      str: 40,
      mag: 0,
      dex: 25,
      spd: 35,
      def: 25,
      res: 30,
      lck: 25,
      bld: 5,
    },
  },
  {
    name: 'Boucheron',
    image: '/assets/units/boucheron.png',
    class: 'Axe Fighter',
    innate: 'Axe',
    sp: 300,
    personal: {
      name: 'Moved to Tears',
      image: '',
      description:
        "When an ally joins a chain attack in this unit's combat, unit deals +2 damage.",
    },
    origin: 'Firene',
    growths: {
      hp: 85,
      str: 20,
      mag: 0,
      dex: 50,
      spd: 45,
      def: 35,
      res: 20,
      lck: 15,
      bld: 20,
    },
  },
  {
    name: 'Céline',
    image: '/assets/units/celine.png',
    class: 'Noble (Céline)',
    innate: 'Tome',
    sp: 300,
    personal: {
      name: 'Gentle Flower',
      image: '',
      description:
        'Recovery items used by allies within 2 spaces heal +50% HP.',
    },
    origin: 'Firene',
    growths: {
      hp: 50,
      str: 35,
      mag: 25,
      dex: 30,
      spd: 45,
      def: 30,
      res: 40,
      lck: 50,
      bld: 5,
    },
  },
  {
    name: 'Chloé',
    image: '/assets/units/chloe.png',
    class: 'Lance Flier',
    innate: 'Lance',
    sp: 300,
    personal: {
      name: 'Fairy-Tale Folk',
      image: '',
      description:
        'If a male and a female ally are adjacent within 2 spaces, unit deals +2 damage during combat.',
    },
    origin: 'Firene',
    growths: {
      hp: 75,
      str: 25,
      mag: 35,
      dex: 40,
      spd: 55,
      def: 30,
      res: 25,
      lck: 25,
      bld: 5,
    },
  },
  {
    name: 'Louis',
    image: '/assets/units/louis.png',
    class: 'Lance Armor',
    innate: 'Lance',
    sp: 300,
    personal: {
      name: 'Admiration',
      image: '',
      description:
        'If two female allies are adjacent within 2 spaces, this unit takes 2 less damage during combat.',
    },
    origin: 'Firene',
    growths: {
      hp: 75,
      str: 40,
      mag: 0,
      dex: 25,
      spd: 25,
      def: 50,
      res: 20,
      lck: 25,
      bld: 15,
    },
  },
  {
    name: 'Yunaka',
    image: '/assets/units/yunaka.png',
    class: 'Thief',
    innate: 'Knife',
    sp: 500,
    personal: {
      name: 'Trained to Kill',
      image: '',
      description:
        'While unit occupies terrain that provides an Avo bonus, grants Crit+15.',
    },
    origin: 'Brodia',
    growths: {
      hp: 50,
      str: 35,
      mag: 25,
      dex: 40,
      spd: 45,
      def: 15,
      res: 45,
      lck: 25,
      bld: 5,
    },
  },
  {
    name: 'Alcryst',
    image: '/assets/units/alcryst.png',
    class: 'Lord (Alcryst)',
    innate: 'Bow',
    sp: 500,
    personal: {
      name: 'Get Behind Me!',
      image: '',
      description:
        'When an ally within 2 spaces is attacked, grants Str+3 to unit for 1 turn.',
    },
    origin: 'Brodia',
    growths: {
      hp: 65,
      str: 30,
      mag: 10,
      dex: 40,
      spd: 45,
      def: 30,
      res: 20,
      lck: 15,
      bld: 10,
    },
  },
  {
    name: 'Citrinne',
    image: '/assets/units/citrinne.png',
    class: 'Mage',
    innate: 'Tome',
    sp: 500,
    personal: {
      name: 'Generosity',
      image: '',
      description:
        'When this unit uses a healing item, adjacent allies also recover the same amount of HP.',
    },
    origin: 'Brodia',
    growths: {
      hp: 45,
      str: 10,
      mag: 40,
      dex: 25,
      spd: 30,
      def: 20,
      res: 40,
      lck: 25,
      bld: 5,
    },
  },
  {
    name: 'Lapis',
    image: '/assets/units/lapis.png',
    class: 'Sword Fighter',
    innate: 'Sword',
    sp: 500,
    personal: {
      name: 'Share Spoils',
      image: '',
      description:
        'If there is an ally within 1 space, grants Hit/Avo+10 at a cost of Crit-10 to unit.',
    },
    origin: 'Brodia',
    growths: {
      hp: 55,
      str: 25,
      mag: 20,
      dex: 35,
      spd: 55,
      def: 35,
      res: 30,
      lck: 25,
      bld: 5,
    },
  },
  {
    name: 'Diamant',
    image: '/assets/units/diamant.png',
    class: 'Lord (Diamant)',
    innate: 'Sword',
    sp: 800,
    personal: {
      name: 'Fair Fight',
      image: '',
      description:
        'If unit initiates combat, grants Hit+15 to unit and for if foe is able to counterattack.',
    },
    origin: 'Brodia',
    growths: {
      hp: 75,
      str: 30,
      mag: 15,
      dex: 20,
      spd: 40,
      def: 40,
      res: 25,
      lck: 20,
      bld: 15,
    },
  },
  {
    name: 'Amber',
    image: '/assets/units/amber.png',
    class: 'Lance Cavalier',
    innate: 'Lance',
    sp: 800,
    personal: {
      name: 'Aspiring Hero',
      image: '',
      description:
        'If no other units are within 1 space of unit or foe, grants Hit+20 at a cost of Avo-10 during combat.',
    },
    origin: 'Brodia',
    growths: {
      hp: 65,
      str: 40,
      mag: 0,
      dex: 25,
      spd: 30,
      def: 35,
      res: 5,
      lck: 35,
      bld: 15,
    },
  },
  {
    name: 'Jade',
    image: '/assets/units/jade.png',
    class: 'Axe Armor',
    innate: 'Axe',
    sp: 800,
    personal: {
      name: 'Meditation',
      image: '',
      description:
        'If unit uses Wait without attacking or using items, grants Res+2 for 1 turn.',
    },
    origin: 'Brodia',
    growths: {
      hp: 55,
      str: 35,
      mag: 25,
      dex: 35,
      spd: 30,
      def: 40,
      res: 30,
      lck: 20,
      bld: 10,
    },
  },
  {
    name: 'Ivy',
    image: '/assets/units/ivy.png',
    class: 'Wing Tamer (Ivy)',
    innate: 'Tome',
    sp: 1000,
    personal: {
      name: 'Single-Minded',
      image: '',
      description:
        "During Combat with a foe who was also unit's most recent opponent, grants Hit+20.",
    },
    origin: 'Elusia',
    growths: {
      hp: 55,
      str: 25,
      mag: 30,
      dex: 25,
      spd: 40,
      def: 30,
      res: 35,
      lck: 15,
      bld: 10,
    },
  },
  {
    name: 'Kagetsu',
    image: '/assets/units/kagetsu.png',
    class: 'Swordmaster',
    innate: 'Sword',
    sp: 1000,
    personal: {
      name: 'Blinding Flash',
      image: '',
      description:
        'If unit initiates combat, inflicts Avo-10 on foe during combat.',
    },
    origin: 'Elusia',
    growths: {
      hp: 60,
      str: 30,
      mag: 15,
      dex: 50,
      spd: 50,
      def: 40,
      res: 25,
      lck: 40,
      bld: 10,
    },
  },
  {
    name: 'Zelkov',
    image: '/assets/units/zelkov.png',
    class: 'Thief',
    innate: 'Knife',
    sp: 1000,
    personal: {
      name: 'Not *Quite*',
      image: '',
      description:
        'If for initiates combat, inflicts Hit-10 on that foe during combat.',
    },
    origin: 'Elusia',
    growths: {
      hp: 65,
      str: 35,
      mag: 15,
      dex: 40,
      spd: 35,
      def: 35,
      res: 15,
      lck: 25,
      bld: 10,
    },
  },
  {
    name: 'Fogado',
    image: '/assets/units/fogado.png',
    class: 'Sentinel (Fogado)',
    innate: 'Bow',
    sp: 1200,
    personal: {
      name: 'Charmer',
      image: '',
      description:
        "During combat with a foe who was also unit's most recent opponent, inflicts Crit-10 on that foe.",
    },
    origin: 'Solm',
    growths: {
      hp: 60,
      str: 30,
      mag: 25,
      dex: 30,
      spd: 55,
      def: 30,
      res: 35,
      lck: 25,
      bld: 10,
    },
  },
  {
    name: 'Pandreo',
    image: '/assets/units/pandreo.png',
    class: 'High Priest',
    innate: 'Staff',
    sp: 1200,
    personal: {
      name: 'Party Animal',
      image: '',
      description:
        'Grants a bonus to Hit and Avo equal to 3x the number of allies and foes within 2 spaces.',
    },
    origin: 'Solm',
    growths: {
      hp: 60,
      str: 5,
      mag: 30,
      dex: 45,
      spd: 45,
      def: 15,
      res: 55,
      lck: 30,
      bld: 15,
    },
  },
  {
    name: 'Bunet',
    image: '/assets/units/bunet.png',
    class: 'Great Knight',
    innate: 'Sword',
    sp: 1200,
    personal: {
      name: 'Seconds?',
      image: '',
      description:
        'On eating a packed lunch, unit may obtain another of the same item. Trigger%=Lck',
    },
    origin: 'Solm',
    growths: {
      hp: 60,
      str: 30,
      mag: 10,
      dex: 40,
      spd: 35,
      def: 45,
      res: 25,
      lck: 40,
      bld: 10,
    },
  },
  {
    name: 'Timerra',
    image: '/assets/units/timerra.png',
    class: 'Sentinel (Timerra)',
    innate: 'Lance',
    sp: 1500,
    personal: {
      name: 'Racket of Solm',
      image: '',
      description: 'Inflicts Crit-5 on foes within 3 spaces.',
    },
    origin: 'Solm',
    growths: {
      hp: 55,
      str: 25,
      mag: 25,
      dex: 45,
      spd: 45,
      def: 30,
      res: 30,
      lck: 30,
      bld: 10,
    },
  },
  {
    name: 'Panette',
    image: '/assets/units/panette.png',
    class: 'Berserker',
    innate: 'Knife',
    sp: 1500,
    personal: {
      name: 'Blood Fury',
      image: '',
      description:
        "If unit's HP is not at max after combat, grants Crit+10 as long a s unit's HP stays below max",
    },
    origin: 'Solm',
    growths: {
      hp: 75,
      str: 45,
      mag: 10,
      dex: 40,
      spd: 25,
      def: 30,
      res: 15,
      lck: 20,
      bld: 15,
    },
  },
  {
    name: 'Merrin',
    image: '/assets/units/merrin.png',
    class: 'Wolf Knight',
    innate: 'Knife',
    sp: 1500,
    personal: {
      name: 'Knightly Escort',
      image: '',
      description:
        'When 2 or more female allies are within 2 spaces, grants Hit/Avo+5 to unit and those allies.',
    },
    origin: 'Solm',
    growths: {
      hp: 55,
      str: 25,
      mag: 25,
      dex: 40,
      spd: 50,
      def: 30,
      res: 30,
      lck: 25,
      bld: 10,
    },
  },
  {
    name: 'Hortensia',
    image: '/assets/units/hortensia.png',
    class: 'Wing Tamer (Hortensia)',
    innate: 'Staff',
    sp: 1500,
    personal: {
      name: 'Big Personality',
      image: '',
      description: 'When unit uses a healing staff, grants range +1.',
    },
    origin: 'Elusia',
    growths: {
      hp: 40,
      str: 20,
      mag: 20,
      dex: 35,
      spd: 50,
      def: 25,
      res: 55,
      lck: 50,
      bld: 0,
    },
  },
  {
    name: 'Seadall',
    image: '/assets/units/seadall.png',
    class: 'Dancer',
    innate: 'Arts',
    sp: 1500,
    personal: {
      name: 'Curious Dance',
      image: '',
      description:
        'At start of turn, allies within 2 spaces of unit recover 10% of their max HP.',
    },
    origin: 'Solm',
    growths: {
      hp: 55,
      str: 25,
      mag: 15,
      dex: 25,
      spd: 50,
      def: 25,
      res: 25,
      lck: 35,
      bld: 10,
    },
  },
  {
    name: 'Rosado',
    image: '/assets/units/rosado.png',
    class: 'Wyvern Knight',
    innate: 'Axe',
    sp: 1800,
    personal: {
      name: 'Stunning Smile',
      image: '',
      description: 'If foe is male, inflicts Avo-20 on that foe during combat.',
    },
    origin: 'Elusia',
    growths: {
      hp: 75,
      str: 45,
      mag: 25,
      dex: 40,
      spd: 45,
      def: 30,
      res: 30,
      lck: 20,
      bld: 5,
    },
  },
  {
    name: 'Goldmary',
    image: '/assets/units/goldmary.png',
    class: 'Hero',
    innate: 'Lance',
    sp: 1800,
    personal: {
      name: 'Disarming Sigh',
      image: '',
      description: 'If foe is male, inflicts Hit-20 on that foe during combat.',
    },
    origin: 'Elusia',
    growths: {
      hp: 65,
      str: 30,
      mag: 5,
      dex: 25,
      spd: 25,
      def: 5,
      res: 25,
      lck: 25,
      bld: 5,
    },
  },
  {
    name: 'Lindon',
    image: '/assets/units/lindon.png',
    class: 'Sage',
    innate: 'Staff',
    sp: 2000,
    personal: {
      name: 'Weapon Insight',
      image: '',
      description:
        "If unit is equipped with a weapon of lower level than foe's, grants Crit+20 during combat.",
    },
    origin: 'Elusia',
    growths: {
      hp: 65,
      str: 25,
      mag: 25,
      dex: 25,
      spd: 40,
      def: 25,
      res: 40,
      lck: 15,
      bld: 10,
    },
  },
  {
    name: 'Saphir',
    image: '/assets/units/saphir.png',
    class: 'Warrior',
    innate: 'Axe',
    sp: 2000,
    personal: {
      name: 'Will to Win',
      image: '',
      description:
        "If unit's HP is 50% or less at start of combat, grants Hit/Avo+20 during combat.",
    },
    origin: 'Brodia',
    growths: {
      hp: 80,
      str: 35,
      mag: 0,
      dex: 25,
      spd: 30,
      def: 30,
      res: 5,
      lck: 20,
      bld: 10,
    },
  },
  {
    name: 'Veyle',
    image: '/assets/units/veyle.png',
    class: 'Fell Child',
    innate: 'Tome',
    sp: 2500,
    personal: {
      name: 'Fell Protection',
      image: '',
      description: 'Adjacent Allies deal +1 damage and take 3 less damage.',
    },
    origin: 'none',
    growths: {
      hp: 40,
      str: 25,
      mag: 45,
      dex: 35,
      spd: 30,
      def: 25,
      res: 35,
      lck: 20,
      bld: 0,
    },
    spoiler: true,
  },
  {
    name: 'Mauvier',
    image: '/assets/units/mauvier.png',
    class: 'Royal Knight',
    innate: 'Staff',
    sp: 2500,
    personal: {
      name: 'Contemplative',
      image: '',
      description:
        'If unit uses Wait without attacking or using items, grants Def+2 for 1 turn.',
    },
    origin: 'none',
    growths: {
      hp: 70,
      str: 35,
      mag: 40,
      dex: 40,
      spd: 35,
      def: 50,
      res: 45,
      lck: 45,
      bld: 15,
    },
    spoiler: true,
  },
  {
    name: 'Anna',
    image: '/assets/units/anna.png',
    class: 'Axe Fighter',
    innate: 'Arts',
    sp: 300,
    personal: {
      name: 'Expertise',
      image: '',
      description:
        'Grants Unit enhanced stat growth when leveling up. (Doubles class Growths)',
    },
    origin: 'Firene',
    growths: {
      hp: 55,
      str: 15,
      mag: 50,
      dex: 50,
      spd: 50,
      def: 20,
      res: 35,
      lck: 45,
      bld: 5,
    },
  },
  {
    name: 'Jean',
    image: '/assets/units/jean.png',
    class: 'Martial Monk',
    innate: 'Bow',
    sp: 300,
    personal: {
      name: 'Make a Killing',
      image: '',
      description: 'May obtain 500G when unit defeats a foe. trigger%=Lck.',
    },
    origin: 'Firene',
    growths: {
      hp: 50,
      str: 20,
      mag: 20,
      dex: 35,
      spd: 40,
      def: 25,
      res: 20,
      lck: 25,
      bld: 5,
    },
  },
];

export default unitData;
